[versions]
agp = "8.9.0"
androidDesugarJdkLibs = "1.2.2"
koinAndroid = "3.2.0"
org-jetbrains-kotlin-android = "2.1.0"
core-ktx = "1.8.0"
junit4 = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.8.0"
kotlin = "2.1.0"
kotlinxCoroutines = "1.6.4"
ksp = "2.1.0-1.0.29"
androidxComposeBom = "2023.06.01"
androidxComposeCompiler = "1.5.0"
constraintlayout = "2.1.4"
gson = "2.8.6"
glide = "4.16.0"
glideTransformations = "4.3.0"
androidutils = "1.31.1"
navigation-fragment-ktx = "2.5.3"
navigation-ui-ktx = "2.5.3"
paging3 = "3.1.1"
androidxLifecycle = "2.6.1"
gms-safetynet = "18.0.1"

#third party
preferenceKtx = "1.2.0"
okhttp = "4.11.0"
localbroadcastmanager = "1.0.0"
room = "2.4.2"
lucksiege-pictureselector = "v3.11.1"
lucksiege-camerax = "v3.10.0"
zelory-compressor = "3.0.1"
compress = "1.18"
broccoli = "1.0.0"
commons-io = "2.11.0"
workRuntimeKtx = "2.9.0"
androidxSqliteFramework = "2.3.0"
activity = "1.8.0"
refresh-layout = "2.1.0"

[libraries]
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }#https://github.com/InsertKoinIO/koin/blob/main/LICENSE
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }#https://github.com/bumptech/glide/blob/master/LICENSE
glide-transformations = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glideTransformations" }#https://github.com/wasabeef/glide-transformations/blob/main/LICENSE
androidutils = { group = "com.blankj", name = "utilcodex", version.ref = "androidutils" }#https://github.com/Blankj/AndroidUtilCode/blob/master/LICENSE

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
#compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

#okhttp
okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}#https://github.com/square/okhttp/blob/master/LICENSE.txt
#localbroadcast
localbroadcastmanager = {group = "androidx.localbroadcastmanager", name= "localbroadcastmanager", version.ref = "localbroadcastmanager"}
#androidx.room
androidx-room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
#PictureSelector basic
lucksiege-pictureselector = { group = "io.github.lucksiege", name = "pictureselector", version.ref = "lucksiege-pictureselector" }#https://github.com/LuckSiege/PictureSelector/blob/version_component/LICENSE
lucksiege-camerax = { group = "io.github.lucksiege", name = "camerax", version.ref = "lucksiege-camerax" }#https://github.com/LuckSiege/PictureSelector/blob/version_component/LICENSE
zelory-compressor = { group = "id.zelory", name = "compressor", version.ref = "zelory-compressor" }#https://github.com/zetbaitsu/Compressor
#paging3
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging3" }
#lifecycle
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
#compress
apache-compress = {group = "org.apache.commons", name="commons-compress", version.ref = "compress"}#https://github.com/apache/commons-compress/blob/master/LICENSE.txt
#broccoli占位动画
broccoli = {group = "me.samlss", name="broccoli", version.ref = "broccoli"}#https://github.com/samlss/Broccoli/blob/master/LICENSE
#safetynet
gms-safetynet = { group = "com.google.android.gms", name = "play-services-safetynet", version.ref = "gms-safetynet" }
#commons io
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }#https://github.com/apache/commons-io/blob/master/LICENSE.txt
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-sqlite-sqlite-framework = { group = "androidx.sqlite", name = "sqlite-framework", version.ref = "androidxSqliteFramework" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
#SmartRefreshLayout
refresh-layout-kernel = { group = "io.github.scwang90", name = "refresh-layout-kernel", version.ref = "refresh-layout" }#https://github.com/scwang90/SmartRefreshLayout/blob/main/LICENSE
refresh-header-classics = { group = "io.github.scwang90", name = "refresh-header-classics", version.ref = "refresh-layout" }#https://github.com/scwang90/SmartRefreshLayout/blob/main/LICENSE
refresh-footer-classics = { group = "io.github.scwang90", name = "refresh-footer-classics", version.ref = "refresh-layout" }#https://github.com/scwang90/SmartRefreshLayout/blob/main/LICENSE

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

